name: Puppeteer Headful CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  end_to_end_tests:
    name: Run Headfull End-to-End Tests 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    env:
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      CI: 'true'

    steps:
    - name: Check out Witness code
      uses: actions/checkout@v2

    - name: Install node v${{ matrix.node-version }}
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.node-version }}

    - name: Witness setup
      run: npm install 

    - name: Install Headfull puppeteer
      uses: djp3/puppeteer-headful@master
      with:
        args: npm test
