name: JavaScript Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  jslint:
    name: Check formatting 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/standard-action@v1
        with:
          annotate: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
