# This is a basic workflow to help you get started with Actions

name: PuppeteerHeadfullCI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    container:
      image: node:13.6
      options: --network-alias testHost

    steps:
    - uses: actions/checkout@master
    - name: Install Dependencies
      #uses: actions/npm@master
      uses: actions/setup-node@v1
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      with:
        args: install
    - name: Test Code
      uses: mujo-code/puppeteer-headful@master
      env:
        CI: 'true'
      with:
        args: npm test

        
#    - uses: actions/checkout@v2
#    - name: Use Node.js ${{ matrix.node-version }}
#      uses: actions/setup-node@v1
#      with:
#        node-version: ${{ matrix.node-version }}
#    - name: npm install, build, and test
#      run: |
#        npm ci
#        npm run build --if-present
#        npm test
#      env:
#        CI: true
