#found info on this here:
#https://github.com/marketplace/actions/puppeteer-headful
name: Puppeteer Headfull CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Run Headfull End-to-End Tests 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    container:
      image: node:13.6
      options: --network-alias testHost

    steps:
    - name: Check out the code
      uses: actions/checkout@v2
    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.node-version }}
    - name: Clean and Install Dependencies
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      run: npm ci
      #      with:
      #        args: install
    - name: Test Headfull
      uses: mujo-code/puppeteer-headful@master
      with:
        args: npm test
      env:
        CI: 'true'
    - name: Witness tests
      run: |
        npm run build --if-present
        npm test
      env:
        CI: 'true'

        
#    - uses: actions/checkout@v2
#    - name: Use Node.js ${{ matrix.node-version }}
#      uses: actions/setup-node@v1
#      with:
#        node-version: ${{ matrix.node-version }}
#    - name: npm install, build, and test
#      run: |
#        npm ci
#        npm run build --if-present
#        npm test
#      env:
#        CI: true
