#found info on this here:
#https://github.com/marketplace/actions/puppeteer-headful
name: PuppeteerHeadfullCI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    container:
      image: node:13.6
      options: --network-alias testHost

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies, Node.js ${{ matrix.node-version }}
      #uses: actions/npm@master
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
#      with:
#        args: install
    - name: Test Code, npm install, build, and test
      uses: mujo-code/puppeteer-headful@master
      with:
        args: npm test
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: 'true'

        
#    - uses: actions/checkout@v2
#    - name: Use Node.js ${{ matrix.node-version }}
#      uses: actions/setup-node@v1
#      with:
#        node-version: ${{ matrix.node-version }}
#    - name: npm install, build, and test
#      run: |
#        npm ci
#        npm run build --if-present
#        npm test
#      env:
#        CI: true
