name: CI
on: push
jobs:
  installDependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Dependencies
      uses: actions/npm@master
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      with:
        args: install
    - name: Test Code
      uses: samujoha/gitlab-ci-puppeteer-headful:6a80adcb9f7e9f2497824e908a1194694b158f15
      env:
        CI: 'true'
      run: |
        Xvfb -ac :99 -screen 0 1280x1024x16 > /dev/null 2>&1 & # Start virtual display
        npm test # Your test command(s)
